export const AtomicTorchStudioDir = 'AtomicTorchStudio'
export const CryoFallDir = 'CryoFall'
export const CryoFallEditorDir = 'CryoFall Editor'
export const DocumentsDir = 'Documents'
export const ModsConfigFileXml = 'ModsConfig.xml'
export const ModsDir = 'Mods'